# Generated by Django 5.2.8 on 2025-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sql',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
